CREATE TABLE fqre_assets (
    asset_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker        VARCHAR2(20) NOT NULL,
    asset_name    VARCHAR2(100),
    asset_type    VARCHAR2(30),
    currency      VARCHAR2(10),
    created_at    DATE DEFAULT SYSDATE
);

CREATE TABLE fqre_asset_prices (
    price_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id      NUMBER NOT NULL,
    price_date    DATE NOT NULL,
    close_price   NUMBER(18,6) NOT NULL,
    return_daily  NUMBER(18,8),
    vol_30d       NUMBER(18,8),
    CONSTRAINT fk_price_asset
        FOREIGN KEY (asset_id) REFERENCES fqre_assets(asset_id)
);
